name: Lint and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.x'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install .
      - name: Test
        run: |
          python -m unittest discover --pattern *_test.py
